# Generated by Django 3.0.5 on 2020-05-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_currency_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='CoinForTable',
        ),
    ]
