# Generated by Django 3.0.5 on 2020-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointable',
            name='name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.CharField(default='default_id', max_length=30),
        ),
        migrations.AlterField(
            model_name='cointable',
            name='coin_id',
            field=models.CharField(default='default_id', max_length=30),
        ),
    ]
