# Generated by Django 3.0.5 on 2020-05-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20200502_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinTable',
            new_name='CoinForTable',
        ),
    ]
