# Generated by Django 3.0.5 on 2020-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_auto_20200502_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinfortable',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
