# Generated by Django 3.0.5 on 2020-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_coinfortable_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinfortable',
            name='beta_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinfortable',
            name='change_24h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinfortable',
            name='circulating_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinfortable',
            name='coin_ranking',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinfortable',
            name='market_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinfortable',
            name='max_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinfortable',
            name='volume_24h',
            field=models.FloatField(default=0.0),
        ),
    ]
